
[window]
padding = { x= 20, y = 20 }
opacity = 0.99

[font]
normal = { family = "Iosevka Nerd Font", style = "Regular" }
size = 13.0

[keyboard]
bindings = [
    { key = "n", mods = "Control", action = "SpawnNewInstance" }
]

[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]
