#shadow
shadow = true;
shadow-radius = 10;
no-dock-shadow = true;
no-dnd-shadow = true;
clear-shadow = true;

#inactive windows
shadow-exclude = ["!focused"];

#backend
backend = "xrender";
glx-swap-method = "buffer-age";
glx-no-rebind-pixmap = true;
glx-no-stencil = true;
paint-no-overlay = true;
unredir-if-possible = false;
xrender-sync-fence = true;
detect-transient = true;
detect-client-leader = true;
shadow-ignored-shaped = true;
detect-round-corners = true;


